### ISSUE TITLE
orphans handled incorrectly when consuming REST services

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-client#17]
per email discussion, it appears that orphan genes do not get a "data-family" attribute in the HTML, causing them to behave a little oddly with respect to their status as orphans (in particular, they get colored and are not highlighted when the orphan class in the legend is hovered; they do get assigned to the orphan lists when the legend glyph is clicked, though).
Seemingly the "correct" structure is to have a data-family attribute without a value (at least, this is what is happening when gRPC services are being used).

**Comment by alancleary** [comment]
Fixed in commit legumeinfo/microservices@6132a76aa063b749bada17fe98415cd8d5d4fb17. It looks like the new version of RediSearch returns null when a field's value is the empty string. The service is now explicitly giving genes without a family an empty string value before sending them to the client.
