### ISSUE TITLE
collision between services and client routes?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv-client#3]
I'm not sure I have expressed the problem well in the issue title, or even understood what the problem is, but here's what I'm seeing. If I am in the client and I do a search for a gene or region, it takes me to the page showing search results, in user-interactable form at a URL like https://legumeinfo.org/gcv2/search?q=vigun.Vu05:46315545-48000000&sources=lis

however, if I go to that URL directly, I just get the search return as JSON:
{"genes": [], "regions": [{"gene": "vigun.Vigun05g278600", "neighbors": 110}]}

I suspect this is because the client happens to be using the same route path as does the service? In any case, it would be 
nice to be able to link into GCV by region, and that's all I'm really trying to do at the moment.

**Comment by alancleary** [comment]
This has been fixed in production, however, a more permanent fix would be to extend the Traefik route prefix in the docker-compose[.prod].yml to distinguish between microservice routes and gcv client routes. Make it so!

**Comment by alancleary** [comment]
Fixed in commit d24fd2f9ff53ef1b212e5a20830fa33358b9bfa0.
